on: [push]
name: Azure ARM for Bpxtest azure2.0 prototype
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        region: ${{ secrets.AZURE_REGION }}
        template: ./docs/reference/contoso/armTemplates/auxiliary/bpxtest-1mgmtGroups.json
        deploymentName: bpx-azure2-mgmt-structure-mvp-spn04-1mgmt

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}