on: [deployment]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Log in with Azure Test3
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account show
          az account management-group create --name Test-Mgmt-3 --parent e8ffc671-bfab-4391-8de4-ccc8d28f8f11
